.gitignore, models.go, oauth.go, package-lock.json, package.json, public/css/application.css, tailwind.config.js, views/application.css, views/apps/index.html, views/apps/show.html, views/layout.html
=> Add tailwind and some UI

config.go, main.go
DataDog automatically loads the config from env variablse like DD_AGENT_HOST
=> Simplify DataDog config

main.go
The previous PR had a bug: we lose connection to the relay after reconnecting.
=> reconnect on relay error

.github/workflows/workflow.yaml
=> Add linux/386 to build workflow

views/layout.html
=> feat: add nwc favicon

views/apps/new.html
typically these names are unique
=> Disable auto-complete

alby.go, models.go, public/css/application.css, views/apps/new.html
Fixes #53
Adds Email to User and displays it in the `apps/new` screen
=> feat: add email

views/apps/new_with_pubkey.html
=> fix: display email in new with pubkey screen too

config.go, main.go
fixes #57 
Copied over the database configuration from lndhub
=> set db config

echo_handlers.go, public/css/application.css, views/apps/index.html, views/layout.html
=> feat: add navigation

public/images/plus.svg, views/apps/create.html, views/apps/index.html
=> chore: fixes

views/apps/create.html
this makes sure the page has a bit time to finish loading.
=> delay redirect slightly

public/css/application.css, views/layout.html
+ see: https://getalby.slack.com/archives/C03CFL7SE56/p1684225708662579
=> always show logout button on mobile.

echo_handlers.go, models.go, public/css/application.css, service.go, views/apps/new.html, views/apps/show.html
Adds recurring budget and expiry
=> feat: add recurring budget and expiry

alby.go, config.go, lnd.go
Attempt to set the domain-level cookies so they can be removed from rails app
=> fix: set domain for cookies

alby.go, config.go, echo_handlers.go, lnd.go, service.go
Fixes the cookie handling when coming from amethyst (apps/new handler)
=> fix: cookie in appsnewhandler

alby.go, echo_handlers.go, views/apps/new.html, views/apps/show.html
Adds CSRF middleware to protect against CSRF attacks
Fixes #90
=> feat: use csrf middleware

views/apps/create.html
=> fix: allow copy in http connections

README.md, alby.go, handle_make_invoice_request.go, handle_payment_request.go, lnd.go, models.go, service.go, service_test.go
Partially addresses https://github.com/getAlby/nostr-wallet-connect/issues/112
=> make_invoice handler

handle_balance_request.go, handle_make_invoice_request.go, handle_payment_request.go, models.go, service.go
I didn't change the values to ensure data consistency, but made the constants a bit more clear what is going on.
=> chore: use constants for nostr event state

alby.go
=> chore: log payment hash if successful

handle_balance_request.go, handle_lookup_invoice_request.go, handle_make_invoice_request.go, handle_payment_request.go, models.go, service.go
Not a go dev so don't totally know what I am doing, feel free to take over this PR
Closes #142
=> Properly return result_type for NWC error responses

service.go
Fixes #93
Adds JSON logging to `expired pubkey` and  `permissions not found`
And also to `StartSubscription`
=> chore: add json logging in unused places

.env.example, README.md, config.go, echo_handlers.go
fixes https://github.com/getAlby/nostr-wallet-connect/issues/160
=> feat: add support both internal and public relay URL

.github/workflows/workflow.yaml
Merge must be coordinated with
https://github.com/getAlby/alby-deployment/pull/230
which splits values.yaml file for simnet cluster into values/*.yaml for each deployment
=>  update simnet yaml files inside values

start.go
infinite loop of retries to reconnect to relay after any error (except for a cancelled context e.g. on user exiting the app)
=> Feat: reconnect to relay
