getAlby/nostr-wallet-connect

config.go, oauth.go
This uses a configurable cookie secret if no secret is configured it generates a random one (which will be different each app start and thus invalidate old cookies)
=> Configurable session cookie secret

echo_handlers.go, lnd.go
this removes the step to go to the homepage and when a user has a deeplink from an app we directly redirect the user to the authentication.
=> Unify auth flow to automatically redirect users from the apps/new deeplink

main.go
This should fix #76, but I haven't tested it yet. If someone would like to review or test, please. Thank you.
=> allow only single concurrent connection for SQLite to prevent lock-up

service.go
=> fix: add check for status and replied at

alby.go, echo_handlers.go, lnd.go, service.go
Fixes the cookie issue, which is stopping logins and logouts
The issue is that the `alby_nostr_wallet_connect` cookie was saved in users' browsers under the [nwc.getalby.com](http://nwc.getalby.com/) subdomain, and currently we add the alby_nostr_wallet_connect cookie under [.getalby.com](http://getalby.com/) domain (and in other places, we don't specify the domain cause it does key value matching and we don't know if we get the cookie with subdomain or main domain). So instead of clearing it @bumi said it's better to rename the cookie.
(apart from the [issue](https://getalby.slack.com/archives/C04FDDHNTJ6/p1687938457797709) Moritz mentioned in slack, you can't also log out if you're logged in already, that's because the cookie which is being cleared is of the subdomain and the main …
=> fix: rename cookie and make it domain level

service.go, service_test.go
Bare bolt11 invoices in the payload were never in NIP-47 but were initially send by Amethyst.
[They don't do that anymore](https://github.com/vitorpamplona/amethyst/blob/787ca98daffca6646f9212286ae55d8b40b1cee3/app/src/main/java/com/vitorpamplona/amethyst/service/model/LnZapPaymentRequestEvent.kt#L88), so we can safely delete this now.
=> remove support for legacy payload

README.md, echo_handlers.go
Note: I decided to still support passing as a date string. This introduces complexity a little but I think it is nice to support both formats. Removing the other would be a breaking change (most likely no-one is using it yet?)
=> feat: allow passing expires_at as a timestamp in seconds

main.go
Fixes #108 
When using sqlite, you need this statement in order to enable foreign key relations and cascade deletes.
=> add foreign key cascade for sqlite

echo_handlers.go, views/404.html, views/apps/index.html, views/apps/show.html
Fixes #91
Also adds a 404 page
=> feat: use pubkey url in apps show handler and add 404 page

echo_handlers.go
=> chore: remove unnecessary logger

echo_handlers.go
Currently `expiryAt` is not parsed properly and is being set as zero everytime, this fixes the layout to parse it correctly
=> fix: parse layout

echo_handlers.go
I think it is more consitent to enable all (or none) by default..
=> Default to enable all request methods

alby.go, echo_handlers.go
this helps to keep the context and give users context related info
=> Pass client app name as state parameter to oauth connection

handle_payment_request.go
This PR closes #184.  
The problem lies in [this](https://github.com/lightningnetwork/lnd/blob/30348baedcd9e9b157c4cdbf7f0c322fff20cc68/zpay32/decode.go#L59-L62) code block of the `decode.go` file in the `zpay32` package of `lnd`:  
```go
if !strings.HasPrefix(hrp[2:], expectedPrefix) {
return nil, fmt.Errorf(
"invoice not for current active network '%s'", net.Name)
}
```
Submitting an uppercase *Bolt11* invoice sets the condition to always be false and triggers that error.  
The associated commit in this pull request enforces the lowercase conversion of the invoice before all the processing take place, thereby eliminating the problem at its root.  
I have tested it using `go test`, and the issue does not arise when hardcoding an uppercase invoice in `service_test.go`
=> fix(handle payment request): lowercase bolt11 invoice

alby.go, lnd.go, models.go, service_test.go
fixes https://github.com/getAlby/nostr-wallet-connect/issues/204
also fixes expiresAt in lndInvoiceToTransaction function (was incorrectly using settledAt)
=> fix: make timestamps numbers to follow NIP-47

.env.example, service.go
Fixes https://github.com/getAlby/nostr-wallet-connect/issues/205
=> fix: remove infinite loop in subscription causing high cpu

api.go, config.go, lnd.go, main.go, migrations/202401161432_add_config_table.go, models/db/db.go, service.go
This PR always sets up a database entry for the config, based off the env if it's not setup yet.
The app can always rely on the database config being available and does not merge configs.
=> feat: config db

service.go, service_test.go
Instead of waiting till we reach EOS in one goroutine and concurrently looping through the already responded events in another goroutine, we can just block till we reach EOS in the same goroutine and then loop through events. That way we don't even have to check if it reached EOS.
And hence removes the need of an additional go routine and the unnecessary check for ReceivedEOS and also removes it from the Service model as a whole.
=> chore: dry up eos

api.go, config.go, frontend/src/App.tsx, frontend/src/components/redirects/AppsRedirect.tsx, frontend/src/components/redirects/HomeRedirect.tsx, frontend/src/components/redirects/SetupRedirect.tsx, frontend/src/constants.ts, frontend/src/screens/Start.tsx, frontend/src/screens/Unlock.tsx, frontend/src/types.ts, http_service.go, models/api/api.go, start.go
=> Feat: unlock screen (WIP)

models.go, service.go
The [NIP](https://github.com/nostr-protocol/nips/blob/master/47.md#events) defines that the info event should be space separated, not comma separated.
Not sure if this needs to be fixed anywhere else, this seems like it'll only be fixed for instances without changed permissions
=> Fix info event to be space separated
